# Generated by Django 4.2 on 2026-09-23 10:09

import assignments.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('classes', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default=assignments.models.current_academic_year, max_length=9)),
                ('term', models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_class_teacher', models.BooleanField(default=False)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='classes.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.teacherprofile')),
            ],
            options={
                'ordering': ['academic_year', 'term', 'classroom'],
            },
        ),
        migrations.AddIndex(
            model_name='teacherassignment',
            index=models.Index(fields=['teacher', 'academic_year', 'term'], name='assignments_teacher_c5a031_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherassignment',
            index=models.Index(fields=['classroom', 'academic_year', 'term'], name='assignments_classro_96daf8_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherassignment',
            index=models.Index(fields=['subject', 'academic_year', 'term'], name='assignments_subject_f2cf7f_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacherassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'classroom', 'subject', 'academic_year', 'term'), name='unique_teacher_class_subject_term'),
        ),
    ]
